### ISSUE TITLE
Self-hosted Gitlab doesn't work

### ISSUE THREAD

**Issue by KamilKleina** [trevorhauter/gitportal.nvim#68]
self-hosted gitlab instance doesn't work correctly
I am in the repo and I am trying to open a file:
path: $REPO/configurations/lib/data_lake/glue.py
and I am getting an error: couldn't determine git host
where host is: https://dev.$COMPANY_NAME.com

and running:
```
git config --get remote.origin.url 
 git@ssh.dev.$COMPANY_NAME.com:random_word/random_word_2/$REPO.git
````

**Comment by trevorhauter** [comment]
Thanks for reporting! I think I know what's going on here. I'll have some time to work on this tomorrow evening

**Comment by trevorhauter** [comment]
@KamilKleina I'm trying to sort out a way to automatically detect/parse these urls. Do you know if the `ssh` preceding `dev.COMPANY_NAME` is a common place thing that should be ignored from the origin url? I have an ssh repo but there is no preceding`ssh`, mine for example looks like this

```sh
git config --get remote.origin.url
git@gitlab.com:gitportal/gitlab-test.git
```

**Comment by trevorhauter** [comment]
@KamilKleina Hey, I just pushed a PR that will hopefully resolve your issue. 

The origin url 
`git@ssh.dev.$COMPANY_NAME.com:random_word/random_word_2/$REPO.git`can now be handled and will translated to 
`https://dev.$COMPANY_NAME.com/random_word/random_word_2/$REPO.git`

Let me know if it's working for you now!

**Comment by KamilKleina** [comment]
Hey man,
still doesn't work, I am getting the same error 

is there some kind of debug mode or something so I can help here more?

**Comment by KamilKleina** [comment]
I think you have problem with that part of code:

```
    for host, host_info in pairs(M.GIT_HOSTS) do
        if string.find(origin_url, host_info.name, 0, true) then
            return host
        end
    end
```

this doesn't support currently any self-hosted url
while you self-host gitlab you will not have anything with that variable so it fails

**Comment by trevorhauter** [comment]
@KamilKleina No, there is currently not a debug mode, I've just created an issue for that here [1].

You're right, the code is incorrectly assuming that there will always be a trace of the git host even in self hosted instances. I hadn't had any experience with self hosted instances before, and incorrectly assumed that would be present during the discussion on the original issue to add support for gitlab [2].

I will start work on adding config options so users with self hosted instances can specify the required information, thanks for the suggestion!

I really appreciate your time and effort helping me get this supported. I'll do my best to get a resolution out ASAP. 

1. https://github.com/trevorhauter/gitportal.nvim/issues/74
2. https://github.com/trevorhauter/gitportal.nvim/issues/51

**Comment by trevorhauter** [comment]
@KamilKleina Alright, there is now an option to specify your git platform, in your case, `gitlab`. Instructions are on the readme, and the wiki has been updated as well with information about the field.

As for URL handling, GitPortal is able to automatically handle your URL, so no configuration is required there. I've added test coverage and did a lot of manual testing with the example remote url
```sh
git@ssh.dev.$COMPANY_NAME.com:random_word/random_word_2/$REPO.git
```
which resolves to
```sh
https://dev.$company_name.com/
```

GitPortal should be able to deduce the https url from the ssh config in most situations. I will still be adding support for custom regexes at some point in this issue: https://github.com/trevorhauter/gitportal.nvim/issues/69

My philosphy for this project is to make GitPortal infer as much as it can, that is, understanding and resolving URLs, hosts, whatever it may be as much as possible, but as I learn the limitations on that I want to also provide the maximum amount of customization so it works for everybody... Hard to strike a balance! Let me know if this is working for you. Thanks again for all of your feedback!

**Comment by KamilKleina** [comment]
Will give it a try and let you know if it doesn't work correctly,
I just got a quick question:
`git_platform = nil, -- Git platform "github"| "gitlab" (auto-detected if nil)`

Let's say I have self-hosted couple different instances that sometimes are gitlab sometimes github, what should I specify that in here? This will be a big use case for me specially since you add something else than gitlab and github

**Comment by trevorhauter** [comment]
@KamilKleina ah, great question. That is something I have been thinking about. At the moment, there is no a way for gitportal to switch between platforms for different self hosted projects, but there definitely should be. I'm going to work on adding a way to map different projects to different platforms. Hopefully at the very least this should work in its current state.

**Comment by KamilKleina** [comment]
@trevorhauter It does work now, when I specify platform as gitlab.
Thank you for fixing it. But I think that's the first thing you need to change. I want to be able to use that plugin with github, gitlab and self-hosted instances at the same time. so at least start with something like:
git_platform_default: nil
git_platform_extras: {
    my_selfhosted_domain: gitlab,
    my_otherselfhosted_domain: github,
 }
 
 so for specific domain I can just overwrite domain or something like it

**Comment by trevorhauter** [comment]
@KamilKleina agreed. I just created an issue and it's the first thing I'll work on. This will be resolved no later than Thursday 12/19. The progress can be tracked over there

https://github.com/trevorhauter/gitportal.nvim/issues/78

**Comment by trevorhauter** [comment]
@KamilKleina Hey! I have just added the new feature that allows you to have different git providers based on your origin url. Instructions are in the readme, and more detail is on the wiki as well. This was added in this issue (now closed) below. Please don't hesitate to open a new issue if you run into any trouble with this!

https://github.com/trevorhauter/gitportal.nvim/issues/78
